# Generated by Django 5.2.6 on 2025-09-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
