# Generated by Django 5.2.6 on 2025-10-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_trade"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="ledger",
            index=models.Index(
                fields=["timestamp"], name="accounts_le_timesta_b21832_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="position",
            index=models.Index(fields=["symbol"], name="accounts_po_symbol_85d9f0_idx"),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["exchange"], name="accounts_st_exchang_47f60c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["symbol", "exchange"], name="accounts_st_symbol_1c4bad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(fields=["symbol"], name="accounts_tr_symbol_aa7ae0_idx"),
        ),
        migrations.AddIndex(
            model_name="trade",
            index=models.Index(
                fields=["timestamp"], name="accounts_tr_timesta_aedcfd_idx"
            ),
        ),
    ]
